<a href="https://colab.research.google.com/github/OlliSensible/HW-Mathematics-for-Computer-Science/blob/HomeWork-1/%D0%94%D0%971_%D0%A1%D0%B5%D0%BD%D1%87%D0%B8%D0%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. У своєму Колабі введи вектор (матрицю розміром `1:8`)* A. Як це зробити - детально показано у конспекті до теми 1 “Вектори, матриці та операції над ними”. Вектор А - показники твого колеса життєвого балансу.

In [ ]:
import numpy as np
A = np.array([ 3,  9,  8, 10, 10, 10, 10, 9])
print(A)

[ 3  9  8 10 10 10 10  9]


2. Обрахуй суму елементів вектора А - це твій теперішній “показник щастя”.


In [ ]:
sum_A = np.sum(A)
print("Показник щастя: ", sum_A)

Показник щастя:  69


3. Введи вектор B. Це показники розподілу твого життя за сферами.


In [ ]:
B = np.array([ 1,  1,  45, 3, 35, 17, 11, 9])
print(B)

[ 1  1 45  3 35 17 11  9]


4. Обрахуй вектор C, що дорівнює C = A / B. Це ефективність твого життя. Тобто скільки "балів щастя" ти отримуєш за 1 годину на тиждень, що приділяєш відповідній сфері.


In [ ]:
C = A / B

print("Eфективність життя: ", C)

Eфективність життя:  [3.         9.         0.17777778 3.33333333 0.28571429 0.58823529
 0.90909091 1.        ]


5. Прийми рішення щодо швидких змін у твоєму житті. Подумай, як би ти хотів перерозподілити час. Запиши результат нового розподілу часу у Google Sheet у стовпчик “Перерозподілена кількість годин” на листі “Математичний апарат” та у Колабі введи її як вектор D.

In [ ]:
D = np.array ([10, 5, 40, 10, 30, 10, 9, 8])
print(D)

[10  5 40 10 30 10  9  8]


6. Обрахуй вектор E, як E = D*C. Це твоя прогнозна задоволеність відповідними сферами життя.
Обрахуй суму елементів вектора E, яка покаже тобі прогнозований показник щастя при швидких змінах у твоєму житті шляхом перерозподілу часу.


In [ ]:
E = D * C
print("Прогнозована задоволеність сферами життя: ", E)


Прогнозована задоволеність сферами життя:  [30.         45.          7.11111111 33.33333333  8.57142857  5.88235294
  8.18181818  8.        ]


7. Обрахуй суму елементів вектора E, яка покаже тобі прогнозований показник щастя при швидких змінах у твоєму житті шляхом перерозподілу часу.

In [ ]:
sum_E = np.sum(E)
print("Прогнозований показник щастя: ", sum_E)

Прогнозований показник щастя:  146.08004413886766


8. Проаналізуй існуючий та прогнозний показники щастя, зроби висновки у будь-якому вигляді, склади короткий план дій для зміни свого життя.

Для вирішення даної задачі мені потрібно зробити такі зміни:
1. Отримати роботу, і якій я буду бачити карєрний рост, що звищіть кількість годин для цього пункту.
2. Дочекатись, коли племінниця трохи підросте, бо показник сімї я поки не можу збільшити... сестра занадто сильно унавлена через те, що тільки 2 місяці тому народила і тому не має часу на мої дзвінки.
3. Зробити день друзів. День, коли я зможу провести цілий день тільки з ними.
4. Треба знизити кількість годин на хобі. Замінити читання звичайних книг, на читання на англіській мові. Таким чином я переросприділю ці години.
5. Зменшити кількість годин на навчання. Це зможу зробити тільки в січні, після закінчення професійного курсу.

Всі інші сфери в зоні комфорту.